### PR TITLE
Rebuilding `Base`

### PR DESCRIPTION
**Pull request by gullitmiranda**
Hi, @bryanjos

I'm writing a lib called [insights](https://github.com/gullitmiranda/insights) which will work as an abstraction layer for insight services (e.g. Keen.io) or key-value database (e.g. Redis).

I like your implementation, so I think it's better I contribute with you than start from scratch a lib that fits my needs. As I'm developing it I'll keep adding improvements and fixes. Feel free to merge it into Keenex code if you want.

Improvements:
- Azkfile.js: I'm from [azk](http://azk.io) core team and it allows using expandable standardized environments, making it easy testing;
- I've updated HTTPotion and redid `Keenex.HTTP` and `Keenex.Base`, adding logic to exempt the need of specify which key should be used in the request;
- Still on `Keenex.Base`, I've added URL normalization which will always add the base URL (API URL + `projects/#{project_id}`), supporting endpoints in both list or string format;
- I've updated `exvcr`: Unfortunately I'm facing issues to run the tests so I've not added tests for the changes I've made. I'm in touch with the maintainer of `exvcr` package through [this issue](https://github.com/parroty/exvcr/issues/24). Now, I'm going to run the tests with elixir v1.0.4 to check if I've found the solution.

### CODE REVIEW

**Comment by bryanjos** [comment]
insights sounds like something I've been wanting to work on for a bit myself! Hopefully I'll be able to contribute to it as well.

My only concern making it seem like azk is required for development. But I think from the instructions, it should be somewhat clear that it's not necessarily needed. We can give it a shot and see how it goes.

Saying all that, the only change I think that should be made is re-adding the lines that were taken from the .gitignore file.

I'm interested in giving azk a spin. Installing now :) As an OS X user, I just haven't had the best experience with boot2docker, but I haven't tried in a couple of months either.

**Comment by gullitmiranda** [comment]
Cool. I'm glad you have been interested in the Insights.

As for the `.gitignore` my fault because when I add the `.azk` removed others. It is already fixed.

[`azk`](http://azk.io) really is not necessary. We can improve this README.md to add forms of performing without the `azk`.

Every day I see people complaining and having problems with boot2docker. We even have had many developing `azk`, therefore we created a fork of [debian2docker](https://github.com/azukiapp/debian2docker) which are keeping.

**Comment by bryanjos** [comment]
Looks good. Thanks!

**Comment by gullitmiranda** [comment]
nice,

I will again enable the testing ExVCR and add more as soon as possible.

But also add some CI service, you have a preference? For example [CircleCI](https://circleci.com), [Travis](https://travis-ci.org/) or [Wercker](http://wercker.com/)?

**Comment by bryanjos** [comment]
No preference here. I'm fine with any of them. Thanks for this btw. At this point I should probably add you as a collaborator.

**Comment by gullitmiranda** [comment]
I will be honored to become a collaborator. :blush:

**Comment by bryanjos** [comment]
Awesome! And thanks!

**Pull request merged**
